event_index:
    path:     /
    defaults: { _controller: "BarathoneventBundle:Event:index" }
    methods:  GET

event_show:
    path:     /{id}/show
    defaults: { _controller: "BarathoneventBundle:Event:show" }
    methods:  GET

event_new:
    path:     /new
    defaults: { _controller: "BarathoneventBundle:Event:new" }
    methods:  [GET, POST]

event_edit:
    path:     /{id}/edit
    defaults: { _controller: "BarathoneventBundle:Event:edit" }
    methods:  [GET, POST]

event_delete:
    path:     /{id}/delete
    defaults: { _controller: "BarathoneventBundle:Event:delete" }
    methods:  [GET, POST, DELETE]

event_addUser:
    path:     /{user}/{event}/add
    defaults: { _controller: "BarathoneventBundle:Event:addUser" }
    methods:  [GET, POST]
event_removeUser:
    path: /{user}/{event}/remove
    defaults:{ _controller: "BarathoneventBundle:Event:removeUser"}
    methods:  [GET, POST, DELETE]