barathonutilisateurs:
    resource: "@BarathonutilisateursBundle/Resources/config/routing.yml"
    prefix:   /utilisateurs

barathonindex:
    resource: "@BarathonindexBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix:   /groupe
