barathonevent:
    resource: "@BarathoneventBundle/Resources/config/routing.yml"
    prefix:   /evenement

barathonbar:
    resource: "@BarathonbarBundle/Resources/config/routing.yml"
    prefix:   /bar

barathonutilisateurs:
    resource: "@BarathonutilisateursBundle/Resources/config/routing.yml"

barathonindex:
    resource: "@BarathonindexBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
