barathonevent:
    resource: "@BarathoneventBundle/Resources/config/routing.yml"
    prefix:   /evenements

barathonbar:
    resource: "@BarathonbarBundle/Resources/config/routing.yml"
    prefix:   /bars

barathonutilisateurs:
    resource: "@BarathonutilisateursBundle/Resources/config/routing.yml"

barathonindex:
    resource: "@BarathonindexBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix:   /groupe
