security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_USER:       ROLE_USER
        ROLE_PROP:        ROLE_PROR
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                # if you are using Symfony < 2.8, use the following config instead:
                # csrf_provider: form.csrf_provider
                always_use_default_target_path : true
                default_target_path: /utilisateurs
                use_referer : true
            logout:       true
            anonymous:    true





    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/evenements/new, role: [ROLE_PROP, ROLE_ADMIN]}
        - { path: ^/evenements/edit, role:[ROLE_PROP, ROLE_ADMIN]}
        - { path: ^/evenements/delete, role: [ROLE_PROP, ROLE_ADMIN] }
        - { path: ^/bars/new, role: [ROLE_PROP, ROLE_ADMIN]}
        - { path: ^/bars/edit, role: [ROLE_PROP, ROLE_ADMIN] }
        - { path: ^/bars/edit, role: [ROLE_PROP, ROLE_ADMIN] }