bar_index:
    path:     /
    defaults: { _controller: "BarathonbarBundle:Bar:index" }
    methods:  GET

bar_show:
    path:     /{id}/show
    defaults: { _controller: "BarathonbarBundle:Bar:show" }
    methods:  GET

bar_new:
    path:     /new
    defaults: { _controller: "BarathonbarBundle:Bar:new" }
    methods:  [GET, POST]

bar_edit:
    path:     /{id}/edit
    defaults: { _controller: "BarathonbarBundle:Bar:edit" }
    methods:  [GET, POST]

bar_delete:
    path:     /{id}/delete
    defaults: { _controller: "BarathonbarBundle:Bar:delete" }
    methods:  DELETE
