bar_index:
    path:     /
    defaults: { _controller: "BarathonbarBundle:Bar:index" }
    methods:  [GET, POST]


bar_index_prop:
    path:     /votrBar/{id}
    defaults: { _controller: "BarathonbarBundle:Bar:indexProp" }
    methods:  GET

bar_show:
    path:     /{id}/detail
    defaults: { _controller: "BarathonbarBundle:Bar:show" }
    methods:  GET

bar_new:
    path:     /nouveau
    defaults: { _controller: "BarathonbarBundle:Bar:new" }
    methods:  [GET, POST]

bar_edit:
    path:     /{id}/modifier
    defaults: { _controller: "BarathonbarBundle:Bar:edit" }
    methods:  [GET, POST]

bar_delete:
    path:     /{id}/supprimer
    defaults: { _controller: "BarathonbarBundle:Bar:delete" }
    methods:  DELETE
