<?php

namespace Barathon\eventBundle\Entity;

/**
 * myEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class myEventRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAll()
    {
        return $this
            ->createQueryBuilder('e')
            ->orderBy('e.date_event', 'DESC')
            ->getQuery()
            ->setMaxResults(5)
            ->getResult()
            ;
    }

    public function getEventProp($id){
        $qb=$this
            ->createQueryBuilder('e')
            ->innerJoin('e.bar_id','b','WITH','b.user_id='.$id)
            ->addSelect('b')
        ;
        return $qb

            ->getQuery()

            ->getResult()

            ;
    }

    public function search($ville, array $category){
        if(empty($category)){
            return $this
                ->findBy( array('ville' => $ville));
        }
    }
}
